DROP TABLE IF EXISTS CONTACT_TEL_DETAIL;
DROP TABLE IF EXISTS CONTACT_HOBBY_DETAIL;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS CONTACT;

DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START 100000;

CREATE TABLE CONTACT (
  ID         INT PRIMARY KEY      DEFAULT nextval('GLOBAL_SEQ'),
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME  VARCHAR NOT NULL,
  BIRTH_DATE TIMESTAMP,
  VERSION    INT         NOT NULL DEFAULT 0,
  CONSTRAINT CONTACT_idx UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE TABLE HOBBY (
  HOBBY_ID VARCHAR PRIMARY KEY  NOT NULL
);

CREATE TABLE CONTACT_TEL_DETAIL (
  ID         INT PRIMARY KEY      DEFAULT nextval('GLOBAL_SEQ'),
  CONTACT_ID INT         NOT NULL,
  TEL_TYPE   VARCHAR NOT NULL,
  TEL_NUMBER VARCHAR NOT NULL,
  VERSION    INT         NOT NULL DEFAULT 0,

  FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (ID)
);

CREATE TABLE CONTACT_HOBBY_DETAIL (
  CONTACT_ID INT         NOT NULL,
  HOBBY_ID   VARCHAR(20) NOT NULL,
  PRIMARY KEY (CONTACT_ID, HOBBY_ID),

  FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (ID),
  FOREIGN KEY (HOBBY_ID) REFERENCES HOBBY (HOBBY_ID)
);
